### ISSUE TITLE
Failed to activate the quickrun package

### ISSUE THREAD

**Issue by sohocoke** [Sixeight/atom-quickrun#1]
1. Install quickrun package
2. Write some ruby code in an untitled file
3. cmd-ctrl-r

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [quickrun](https://github.com/Sixeight/atom-quickrun) package, v0.3.0
### Stack Trace

Failed to activate the quickrun package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/user1/.atom/packages/quickrun/lib/quickrun.coffee:21:23)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:52.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:51.6.0 application:new-file (div.settings-view.pane-item)
     -0:50.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:49.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:46.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:46.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:45.9.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:18.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:15.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:06.0 quickrun:execute (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-diff-details",
      "language-SCSS",
      "Termrk",
      "package-sync",
      "atom-coffee-repl",
      "git-diff-popup",
      "symbols-view",
      "slim-language",
      "language-slim"
    ],
    "themes": [
      "atom-light-ui",
      "SyntaxHighlighter-Reloaded"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sass-Syntax-Highlight, v0.1.1
SyntaxHighlighter-Reloaded, v0.2.0
atom-ctags, v4.1.4
atom-sync, v0.5.2
atomatigit, v1.5.3
browser-plus, v0.0.25
coffee-navigator, v0.0.16
color-picker, v2.0.11
fold-functions, v0.2.1
foldingtext-for-atom, v0.9.0
git-log, v0.4.1
highlight-selected, v0.10.1
jshint, v1.3.9
jsonlint, v1.1.2
language-log, v0.5.0
linter-csslint, v0.0.14
linter-haml, v0.4.0
linter-pylint, v0.2.2
linter-ruby, v0.1.6
linter-scss-lint, v1.0.5
linter-slim, v0.5.1
linter-xmllint, v0.0.7
live-archive, v0.1.15
make-executable, v0.1.1
minimap, v4.12.0
pigments, v0.8.4
project-manager, v1.15.11
project-view, v0.1.2
quickrun, v0.3.0
ruby-slim, v0.2.0
save-session, v0.15.7
symbol-gen, v1.0.0
symbols-tree-view, v0.9.3
sync-on-save, v0.1.3
tree-view-git-modified, v0.5.10
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by Sixeight** [comment]
Thank you for your feedback :pray: 
Please try to set filetype `ruby` or `perl` or `python`.
(you can set filetype using `Shift-Ctrl-L`)

**Comment by Sixeight** [comment]
I've  fixed bug and release new version.
Thank you feedback!

**Comment by sohocoke** [comment]
Nice one.
